
export const customEmojis = [
  {
    id: "project_management",
    name: "Project Management",
    emojis: [
      { id: "📈", name: "Growth Chart", keywords: ["chart", "growth", "progress", "analytics"] },
      { id: "📊", name: "Bar Chart", keywords: ["chart", "statistics", "data", "report"] },
      { id: "📋", name: "Clipboard", keywords: ["tasks", "checklist", "todo", "notes"] },
      { id: "📅", name: "Calendar", keywords: ["schedule", "date", "event", "planning", "deadline"] },
      { id: "🎯", name: "Direct Hit", keywords: ["goal", "target", "objective", "milestone"] },
      { id: "⏳", name: "Hourglass Done", keywords: ["time", "deadline", "pending", "waiting"] },
      { id: "⏱️", name: "Stopwatch", keywords: ["time", "timer", "duration", "performance"] },
      { id: "🚩", name: "Triangular Flag", keywords: ["milestone", "important", "flag", "marker"] },
      { id: "🚦", name: "Vertical Traffic Light", keywords: ["status", "progress", "phase", "gate"] },
      { id: "🚀", name: "Rocket", keywords: ["launch", "release", "liftoff", "go-live", "deploy"] },
      { id: "💡", name: "Light Bulb", keywords: ["idea", "innovation", "solution", "concept"] },
      { id: "🔗", name: "Link", keywords: ["connection", "url", "attachment", "reference"] },
      { id: "📌", name: "Pushpin", keywords: ["important", "save", "bookmark", "reminder"] },
      { id: "⚙️", name: "Gears", keywords: ["settings", "process", "workflow", "configuration"] },
      { id: "🧩", name: "Puzzle Piece", keywords: ["component", "module", "integration", "solution"] },
      { id: "🗺️", name: "World Map", keywords: ["scope", "global", "overview", "strategy"] },
      { id: "🧐", name: "Face with Monocle", keywords: ["review", "inspect", "quality", "detail"] },
      { id: "🤔", name: "Thinking Face", keywords: ["planning", "strategy", "consideration", "decision"] },
      { id: "✍️", name: "Writing Hand", keywords: ["document", "sign-off", "authoring", "notes"] },
      { id: "✅", name: "Check Mark Button", keywords: ["complete", "done", "success", "approved", "task"] },
      { id: "📝", name: "Memo", keywords: ["note", "document", "details", "brief"] },
      { id: "📂", name: "File Folder", keywords: ["files", "storage", "organization", "documents"] },
      { id: "🗂️", name: "Card Index Dividers", keywords: ["organize", "index", "categorize", "files"] },
      { id: "🏗️", name: "Building Construction", keywords: ["build", "development", "wip", "structure"] },
      { id: "🧾", name: "Receipt", keywords: ["billing", "invoice", "budget", "expense"] },
      { id: "🖇️", name: "Paperclip", keywords: ["attachment", "document", "linked"] },
    ],
  },
  {
    id: "business_b2b",
    name: "Business & B2B",
    emojis: [
      { id: "💼", name: "Briefcase", keywords: ["work", "business", "portfolio", "corporate"] },
      { id: "🤝", name: "Handshake", keywords: ["deal", "agreement", "partnership", "b2b"] },
      { id: "💰", name: "Money Bag", keywords: ["finance", "profit", "investment", "revenue"] },
      { id: "💵", name: "Dollar Banknote", keywords: ["money", "currency", "payment", "usd"] },
      { id: "💶", name: "Euro Banknote", keywords: ["money", "currency", "payment", "eur"] },
      { id: "🏢", name: "Office Building", keywords: ["company", "headquarters", "corporate", "enterprise"] },
      { id: "🏦", name: "Bank", keywords: ["finance", "institution", "transaction", "investment"] },
      { id: "📉", name: "Downward Trend", keywords: ["loss", "decline", "risk", "market"] },
      { id: "💹", name: "Chart with Yen", keywords: ["growth", "market", "stocks", "finance", "forex"] },
      { id: "👔", name: "Necktie", keywords: ["formal", "corporate", "professional", "executive"] },
      { id: "🧑‍💼", name: "Office Worker", keywords: ["employee", "staff", "professional", "client", "hr"] },
      { id: "💳", name: "Credit Card", keywords: ["payment", "transaction", "purchase", "finance"] },
      { id: "✈️", name: "Airplane", keywords: ["travel", "global", "international", "logistics"] },
      { id: "🌍", name: "Globe Europe-Africa", keywords: ["global", "international", "market", "world"] },
      { id: "⚖️", name: "Balance Scale", keywords: ["legal", "compliance", "ethics", "decision"] },
      { id: "📄", name: "Page with Curl", keywords: ["document", "contract", "report", "file"] },
      { id: "📢", name: "Loudspeaker", keywords: ["announcement", "marketing", "pr", "broadcast"] },
    ],
  },
  {
    id: "teams_collaboration",
    name: "Teams & Collaboration",
    emojis: [
      { id: "👩‍💻", name: "Woman Technologist", keywords: ["developer", "engineer", "coder", "tech", "female"] },
      { id: "🧑‍💻", name: "Technologist", keywords: ["developer", "engineer", "coder", "tech", "software"] },
      { id: "👨‍💻", name: "Man Technologist", keywords: ["developer", "engineer", "coder", "tech", "male"] },
      { id: "🧑‍🤝‍🧑", name: "People Holding Hands", keywords: ["team", "partnership", "unity", "support", "group"] },
      { id: "👥", name: "Busts in Silhouette", keywords: ["users", "team", "group", "members", "community"] },
      { id: "🗣️", name: "Speaking Head", keywords: ["communication", "meeting", "discussion", "voice"] },
      { id: "💬", name: "Speech Balloon", keywords: ["chat", "message", "discussion", "comment"] },
      { id: "🗨️", name: "Left Speech Bubble", keywords: ["talk", "dialogue", "communication"] },
      { id: "🙌", name: "Raising Hands", keywords: ["celebrate", "support", "agreement", "praise", "teamwork"] },
      { id: "👍", name: "Thumbs Up", keywords: ["approval", "agree", "like", "good", "ok"] },
      { id: "💡", name: "Light Bulb", keywords: ["brainstorm", "shared idea", "innovation", "suggestion"] },
      { id: "🧩", name: "Puzzle Piece", keywords: ["teamwork", "collaboration", "fit", "component", "integration"] },
      { id: "🔄", name: "Anticlockwise Arrows", keywords: ["sync", "iteration", "feedback loop", "agile"] },
      { id: "📣", name: "Megaphone", keywords: ["coordination", "broadcast", "announcement", "share"] },
      { id: "🔗", name: "Link", keywords: ["shared resource", "connection", "collaboration tool"] },
    ],
  },
  {
    id: "general_tools_work",
    name: "General Tools & Work",
    emojis: [
      { id: "🔧", name: "Wrench", keywords: ["tool", "fix", "settings", "utility"] },
      { id: "🔨", name: "Hammer", keywords: ["tool", "build", "construct", "fix"] },
      { id: "🛠️", name: "Hammer and Wrench", keywords: ["tools", "repair", "maintenance", "build"] },
      { id: "🔩", name: "Nut and Bolt", keywords: ["hardware", "fastener", "component", "parts"] },
      { id: "🧰", name: "Toolbox", keywords: ["tools", "kit", "resources", "equipment"] },
      { id: "🔑", name: "Key", keywords: ["access", "security", "login", "solution"] },
      { id: "💻", name: "Laptop", keywords: ["computer", "work", "technology", "device"] },
      { id: "🖥️", name: "Desktop Computer", keywords: ["workstation", "office", "technology"] },
      { id: "📱", name: "Mobile Phone", keywords: ["communication", "app", "contact", "device"] },
      { id: "⌨️", name: "Keyboard", keywords: ["input", "typing", "writing", "code"] },
      { id: "🖱️", name: "Computer Mouse", keywords: ["click", "select", "navigate", "input"] },
      { id: "🖨️", name: "Printer", keywords: ["document", "print", "hardcopy", "office"] },
      { id: "💾", name: "Floppy Disk", keywords: ["save", "file", "data", "storage_legacy"] },
      { id: "☁️", name: "Cloud", keywords: ["storage", "backup", "online", "saas", "data", "hosting"] },
      { id: "🔒", name: "Lock", keywords: ["security", "private", "secure", "access", "auth"] },
      { id: "🔓", name: "Unlock", keywords: ["access", "open", "public", "permission", "auth"] },
      { id: "🛡️", name: "Shield", keywords: ["security", "protection", "defense", "privacy", "firewall"] },
      { id: "🔍", name: "Magnifying Glass Left", keywords: ["search", "find", "lookup", "research", "discover"] },
      { id: "✏️", name: "Pencil", keywords: ["edit", "draft", "write", "draw", "note"] },
      { id: "🗑️", name: "Wastebasket", keywords: ["delete", "remove", "trash", "discard"] },
      { id: "✨", name: "Sparkles", keywords: ["new", "feature", "improvement", "highlight", "clean", "magic"] },
      { id: "🎉", name: "Party Popper", keywords: ["launch", "release", "celebrate", "success", "event", "milestone"] },
      { id: "🔥", name: "Fire", keywords: ["urgent", "critical", "hot", "important", "issue", "incident"] },
      { id: "🔔", name: "Bell", keywords: ["notification", "alert", "reminder", "update"] },
    ],
  },
  {
    id: "computer_science_code",
    name: "Computer Science & Code",
    emojis: [
      { id: "💻", name: "Laptop", keywords: ["code", "develop", "programming", "computer"] }, // Re-used
      { id: "🧑‍💻", name: "Technologist", keywords: ["developer", "coder", "programmer", "software"] }, // Re-used
      { id: "📜", name: "Scroll", keywords: ["code", "script", "log", "history", "source"] },
      { id: "🧠", name: "Brain", keywords: ["ai", "machine learning", "logic", "intelligence", "neural network"] },
      { id: "🤖", name: "Robot Face", keywords: ["automation", "bot", "ai", "script", "program"] },
      { id: "🌐", name: "Globe with Meridians", keywords: ["internet", "network", "web", "http", "api"] },
      { id: "☁️", name: "Cloud", keywords: ["cloud computing", "aws", "azure", "gcp", "serverless", "hosting"] }, // Re-used
      { id: "📦", name: "Package", keywords: ["library", "dependency", "module", "npm", "docker", "container"] },
      { id: "🧱", name: "Brick", keywords: ["component", "framework", "module", "architecture", "build"] },
      { id: "🔗", name: "Link", keywords: ["api", "pointer", "data structure", "hyperlink", "network"] }, // Re-used
      { id: "⚙️", name: "Gears", keywords: ["algorithm", "engine", "backend", "processing", "system"] }, // Re-used
      { id: "↔️", name: "Left-Right Arrow", keywords: ["data flow", "api", "request-response", "communication"] },
      { id: "🔄", name: "Anticlockwise Arrows", keywords: ["loop", "recursion", "process", "sync", "agile"] }, // Re-used
      { id: "✔️", name: "Check Mark", keywords: ["test", "pass", "validation", "ci", "true"] },
      { id: "❌", name: "Cross Mark", keywords: ["error", "bug", "fail", "test", "false", "exception"] },
      { id: "🐛", name: "Bug", keywords: ["debug", "error", "issue", "glitch", "fix"] },
      { id: "🛡️", name: "Shield", keywords: ["cybersecurity", "infosec", "encryption", "auth", "firewall"] }, // Re-used
      { id: "🔑", name: "Key", keywords: ["encryption", "decryption", "auth", "secret", "token", "ssh"] }, // Re-used
      { id: "🔢", name: "Input Numbers", keywords: ["data type", "integer", "float", "math", "algorithm"] },
      { id: "🔣", name: "Input Symbols", keywords: ["regex", "syntax", "special characters", "language"] },
      { id: "➡️", name: "Right Arrow", keywords: ["function call", "next step", "flow", "pipeline", "pointer"] },
      { id: " drzewo", name: "Tree Structure", keywords: ["data structure", "tree", "hierarchy", "dom", "graph"], id: "🌳" }, // Example: If 'tree' symbol isn't a single emoji, use an existing one and rename
      { id: "♾️", name: "Infinity", keywords: ["loop", "infinite loop", "scalability", "mathematics"] },
      { id: "🧪", name: "Test Tube", keywords: ["test", "experiment", "alpha", "beta", "unit test", "integration test"] }, // Re-used
      { id: "🤓", name: "Nerd Face", keywords: ["developer", "geek", "techie", "coder"] },
      { id: "🧬", name: "DNA", keywords: ["bioinformatics", "genetic algorithm", "complex data"] },
    ],
  },
];